### ISSUE TITLE
how about this be turned into a broadcast system - caching is good, broadcast is best!

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/turtlecoin-api-proxy#2]
here is an idea - instead of every browser asking the ~~daemon for an answer (this is what the code looks like to me)~~ proxy for info, setup a socket.io service (probably easiest to do it via https://www.actionherojs.com/ since it has all the building blocks for something like this) where the browser subscribes to a websocket and waits for pushes.

node service runs and polls each daemon once per second, stores the value and pushes it out to connected clients. boom, ~~gone from a self ddos system to a broadcast system~~ instant updates and tracking, could put fancy green/lights on it as well - what you think?

Also since the node service goes and polls, can set a config file with ip:ports or urls or whatever.
can still generate the events thing to do stuff, could even add webhooks to go post or get some endpoint. this then scales for decoupling things :)

**Comment by brandonlehmann** [comment]
@SoreGums Take a look at https://github.com/turtlecoin/turtlecoin-api-proxy/blob/e238d8a216262850b9576058d86dce1fa36d9458/turtlecoin-api-proxy.js#L13  It has a static set of nodes that are polled constantly (w/o requests from clients).

As for once a second (1s) that's a bit much as the target block time is 30s. By default, the cache entries expire after 30s. That cache expiry is configurable in the constructor if you want it faster. The last thing you're want to do is bombard the node with requests for data that doesn't change that fast.

As for the WSS, I'm all for it. I am; however, more familiar with *socket.io* so I'd probably go down that road to setup WSS in the service.

**Comment by SoreGums** [comment]
I don't mind how things are done :)

Pretty sure actionhero uses socket as the WSS implementation (google says no, it uses an even higher level one that lets you select between 3x of them where socket.io is one, nice). ActionHero is a framework, so you can focus on the details instead of how to route things etc.

for sure per 1 second is probably too much, however not really if the daemon is solid 😉 ideally those requests should be served in less than 10ms given that the info to be read should be in ram, and other reasons. (we'll get there eventually!!)

opening up a wss gateway to info is a step towards an app being the middleman between pools and daemon, then the next step would be to rip out the pool internals and replace it with this, if you know what I'm saying. seems like it would be faster to do it this way then to fix the cpp daemon....

**Comment by brandonlehmann** [comment]
Sorry, completely forgot about this... but sockets coming next. SQL DB backend in beta.

**Comment by SoreGums** [comment]
all good, got wss in turtlecoind-ha now.

so could easily tweak this to use that.

**Comment by brandonlehmann** [comment]
I like your thought process... just gonna close this one up because I'm gonna end up re-writing this entire thing anyways.
